export const FETCH_CASES_SUCCESS = 'FETCH_CASES_SUCCESS';
export const FETCH_CASES_FAIL = 'FETCH_CASES_FAIL';

export const CREATE_CASE_SUCCESS = 'CREATE_CASE_SUCCESS';
export const CREATE_CASE_FAIL = 'CREATE_CASE_FAIL';

export const REMOVE_CASE_SUCCESS = 'REMOVE_CASE_SUCCESS';
export const REMOVE_CASE_FAIL = 'REMOVE_CASE_FAIL';
