export const FETCH_SOLUTIONS_REQUEST = 'FETCH_SOLUTIONS_REQUEST';
export const FETCH_SOLUTIONS_SUCCESS = 'FETCH_SOLUTIONS_SUCCESS';
export const FETCH_SOLUTIONS_FAIL = 'FETCH_SOLUTIONS_FAIL';

export const CREATE_SOLUTION_REQUEST = 'CREATE_SOLUTION_REQUEST';
export const CREATE_SOLUTION_SUCCESS = 'CREATE_SOLUTION_SUCCESS';
export const CREATE_SOLUTION_FAIL = 'CREATE_SOLUTION_FAIL';
