export const FETCH_SOLUTIONS_SUCCESS = 'FETCH_SOLUTIONS_SUCCESS';
export const FETCH_SOLUTIONS_FAIL = 'FETCH_SOLUTIONS_FAIL';

export const CREATE_SOLUTION_SUCCESS = 'CREATE_SOLUTION_SUCCESS';
export const CREATE_SOLUTION_FAIL = 'CREATE_SOLUTION_FAIL';

export const UPDATE_SOLUTION_SUCCESS = 'UPDATE_SOLUTION_SUCCESS';
export const UPDATE_SOLUTION_FAIL = 'UPDATE_SOLUTION_FAIL';

export const REMOVE_SOLUTION_SUCCESS = 'REMOVE_SOLUTION_SUCCESS';
export const REMOVE_SOLUTION_FAIL = 'REMOVE_SOLUTION_FAIL';
